name: alemeno
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  awesome_notifications: ^0.8.2
  bloc: ^8.1.2
  cloud_firestore: ^4.13.6
  device_preview: ^1.1.0
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  sizer: ^2.0.15
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
