// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGHugA1x9mYDFZYzXROU7NCR1tsLxtSwM',
    appId: '1:315177451379:web:834961165857589e700f06',
    messagingSenderId: '315177451379',
    projectId: 'alemeno-787d2',
    authDomain: 'alemeno-787d2.firebaseapp.com',
    storageBucket: 'alemeno-787d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgFkcyY6tYLE5W71PXf5HXP1em2ePDhLA',
    appId: '1:315177451379:android:c1dc501375fd4971700f06',
    messagingSenderId: '315177451379',
    projectId: 'alemeno-787d2',
    storageBucket: 'alemeno-787d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABC1wtPhTqiFDgz3x0imXYtL40o59VBHI',
    appId: '1:315177451379:ios:818d92a24d79ca1e700f06',
    messagingSenderId: '315177451379',
    projectId: 'alemeno-787d2',
    storageBucket: 'alemeno-787d2.appspot.com',
    iosBundleId: 'com.nxs.alemeno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABC1wtPhTqiFDgz3x0imXYtL40o59VBHI',
    appId: '1:315177451379:ios:1bf3f94e8d2dfb99700f06',
    messagingSenderId: '315177451379',
    projectId: 'alemeno-787d2',
    storageBucket: 'alemeno-787d2.appspot.com',
    iosBundleId: 'com.nxs.alemeno.RunnerTests',
  );
}
